### ISSUE TITLE
Upgrade to latest from 2.6

### ISSUE THREAD

**Issue by thimmaiah** [ankane/blazer#455]
I get this error when I upgraded to the latest version from 2.6. I guess some additional tables were added? Is there a migration script that needs to be run? Thanks

 undefined method `blazer_maps?' for #<ActionView::Base:0x00000000187dd8>

**Comment by ankane** [comment]
Hi @thimmaiah, `blazer_maps?` is no longer in the codebase, so I'm guessing Blazer is being patched in your application.
